on:
  workflow_call:
    inputs:
      appDirectory:
        required: true
        type: string
      additionalBuildArguments:
        required: false
        default: ''
        type: string
      buildApk:
        required: false
        default: true
        type: boolean
      buildBundle:
        required: false
        default: true
        type: boolean
      upload:
        required: false
        default: false
        type: boolean
    secrets:
      keyStore:
        required: true
      keyStorePassword:
        required: true
      keyPassword:
        required: true
      keyAlias:
        required: true
      googleApiKey:
        required: false
      

jobs:
  build_android:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2

      - name: Set Build Number
        shell: bash
        run: |
          buildNumber=$(.github/scripts/generate_build_number.sh "./${{ inputs.appDirectory }}/pubspec.yaml" $GITHUB_RUN_NUMBER)
          echo BUILD_NUMBER=$buildNumber >> $GITHUB_ENV
      - name: Setup Signing
        env:
          keyPropertiesPath: ${{ github.workspace }}/${{ inputs.appDirectory }}/android/key.properties
          keystorePath: ${{ github.workspace }}/${{ inputs.appDirectory }}/android/key.jks
          androidKeyStore: ${{ secrets.keyStore }}
          keyStorePassword: ${{ secrets.keyStorePassword }}
          keyPassword: ${{ secrets.keyPassword }}
          keyAlias: ${{ secrets.keyAlias }}
        run: |
          echo ${{ env.androidKeyStore }} | base64 --decode > ${{ env.keystorePath }}
          echo storePassword=${{ env.keyStorePassword }} >> ${{ env.keyPropertiesPath }}
          echo keyPassword=${{ env.keyPassword }} >> ${{ env.keyPropertiesPath }}
          echo keyAlias=${{ env.keyAlias }} >> ${{ env.keyPropertiesPath }}
          echo storeFile=${{ env.keystorePath }} >> ${{ env.keyPropertiesPath }}
      - name: Build Apk
        if: inputs.buildApk
        working-directory: ${{ inputs.appDirectory }}
        run: flutter build apk --build-number=${{ env.BUILD_NUMBER }} ${{ inputs.additionalBuildArguments}}
      - name: Build Bundle
        if: inputs.buildBundle
        working-directory: ${{ inputs.appDirectory }}
        run: flutter build appbundle --build-number=${{ env.BUILD_NUMBER }} ${{ inputs.additionalBuildArguments}}
      - name: Copy Google Key
        if: inputs.upload && secrets.googleApiKey != null && github.event_name != 'pull_request'
        run: |
          keyLocation=${{ github.workspace}}/${{ inputs.appDirectory }}/android/uploadKey.json
          echo "${{ secrets.googleApiKey }} > $keyLocation
          echo GOOGLE_UPLOAD_KEY=$keyLocation >> $GITHUB_ENV
      - name: Upload to Google Play
        if: inputs.upload && secrets.googleApiKey != null && github.event_name != 'pull_request'
        uses: maierj/fastlane-action@v2.2.0
        with:
          verbose: true
          lane: uploadApp
          subdirectory: ./${{ inputs.appDirectory }}/android
          bundle-install-path: 'vendor/bundle'