on:
  workflow_call:
    inputs:
      setup:
        required: false
        default: true
        type: boolean
      lint:
        required: false
        default: true
        type: boolean
      test:
        required: false
        default: true
        type: boolean

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v1

      - name: Setup
        if: ${{ inputs.setup }}
        run: melos run setup
      - name: Format, Lint, Publishability
        if: ${{ inputs.lint }}
        run: melos run lint:all
      - name: Run Tests
        if: ${{ inputs.test }}
        run: melos run test:coverage:all
      - name: Archive Golden failures
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Golden failures
          retention-days: 2
          path: |
            **/test/**/failures/**/*.*
