on:
  workflow_call:
    inputs:
      setup:
        required: false
        default: true
        type: boolean
      lint:
        required: false
        default: true
        type: boolean
      test:
        required: false
        default: true
        type: boolean
      lfs:
        required: false
        default: false
        type: boolean
      runner:
        required: false
        type: string
        default: ubuntu-latest
      flutterVersion:
        required: false
        type: string

    secrets:
      gitDependencyToken:
        description: Token with read access to private GitHub repositories referenced as git dependencies in pubspec.yaml
        required: false

jobs:
  quality:
    name: Quality Checks
    runs-on: ${{ inputs.runner }}
    env:
      GIT_DEPENDENCY_TOKEN: ${{ secrets.gitDependencyToken }}

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: ${{ inputs.lfs }}
      - name: Git credentials for private dependencies
        if: ${{ env.GIT_DEPENDENCY_TOKEN != '' }}
        run: git config --global url."https://x-access-token:${GIT_DEPENDENCY_TOKEN}@github.com/".insteadOf "https://github.com/"
      - name: Checkout LFS objects
        if: ${{ inputs.lfs }}
        run: git lfs checkout
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutterVersion }}
      - uses: bluefireteam/melos-action@v1

      - name: Setup
        if: ${{ inputs.setup }}
        run: melos run setup
      - name: Format, Lint, Publishability
        if: ${{ inputs.lint }}
        run: melos run lint:all
      - name: Run Tests
        if: ${{ inputs.test }}
        run: melos run test:coverage:all
      - name: Archive Golden failures
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Golden failures
          retention-days: 2
          path: |
            **/test/**/failures/**/*.*
